//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Accounting.Locales.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Code.
        /// </summary>
        public static string AccountCode {
            get {
                return ResourceManager.GetString("AccountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountNo.
        /// </summary>
        public static string AccountNo {
            get {
                return ResourceManager.GetString("AccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddItem.
        /// </summary>
        public static string Add_Item {
            get {
                return ResourceManager.GetString("Add Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount in Words.
        /// </summary>
        public static string AmountInWords {
            get {
                return ResourceManager.GetString("AmountInWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account List.
        /// </summary>
        public static string BankAccountList {
            get {
                return ResourceManager.GetString("BankAccountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Number.
        /// </summary>
        public static string BillNumber {
            get {
                return ResourceManager.GetString("BillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Account List.
        /// </summary>
        public static string ChartAccountList {
            get {
                return ResourceManager.GetString("ChartAccountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Of Account List.
        /// </summary>
        public static string ChartOfAccountList {
            get {
                return ResourceManager.GetString("ChartOfAccountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Bank Account.
        /// </summary>
        public static string CreateBankAccount {
            get {
                return ResourceManager.GetString("CreateBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer.
        /// </summary>
        public static string CreateCustomer {
            get {
                return ResourceManager.GetString("CreateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Daily Transaction.
        /// </summary>
        public static string CreateDailyTransaction {
            get {
                return ResourceManager.GetString("CreateDailyTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Expense Entry.
        /// </summary>
        public static string CreateExpenseEntry {
            get {
                return ResourceManager.GetString("CreateExpenseEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Purchase Entry.
        /// </summary>
        public static string CreatePurchaseEntry {
            get {
                return ResourceManager.GetString("CreatePurchaseEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerID.
        /// </summary>
        public static string CustomerID {
            get {
                return ResourceManager.GetString("CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date (English).
        /// </summary>
        public static string Date_English_ {
            get {
                return ResourceManager.GetString("Date(English)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date (Nepali).
        /// </summary>
        public static string Date_Nepali_ {
            get {
                return ResourceManager.GetString("Date(Nepali)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Amount.
        /// </summary>
        public static string DebitAmount {
            get {
                return ResourceManager.GetString("DebitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit/Credit.
        /// </summary>
        public static string DebitCredit {
            get {
                return ResourceManager.GetString("DebitCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Bank Account.
        /// </summary>
        public static string EditBankAccount {
            get {
                return ResourceManager.GetString("EditBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Chart Account.
        /// </summary>
        public static string EditChartAccount {
            get {
                return ResourceManager.GetString("EditChartAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Customer.
        /// </summary>
        public static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Daily Transaction.
        /// </summary>
        public static string EditDailyTransaction {
            get {
                return ResourceManager.GetString("EditDailyTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Category.
        /// </summary>
        public static string ExpenseCategory {
            get {
                return ResourceManager.GetString("ExpenseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Date.
        /// </summary>
        public static string ExpenseDate {
            get {
                return ResourceManager.GetString("ExpenseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Description.
        /// </summary>
        public static string ExpenseDescription {
            get {
                return ResourceManager.GetString("ExpenseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Year.
        /// </summary>
        public static string FiscalYear {
            get {
                return ResourceManager.GetString("FiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date Nepali.
        /// </summary>
        public static string FromDateNepali {
            get {
                return ResourceManager.GetString("FromDateNepali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Particulars.
        /// </summary>
        public static string ItemParticulars {
            get {
                return ResourceManager.GetString("ItemParticulars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Charges.
        /// </summary>
        public static string OtherCharges {
            get {
                return ResourceManager.GetString("OtherCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN Number.
        /// </summary>
        public static string PAN {
            get {
                return ResourceManager.GetString("PAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particular.
        /// </summary>
        public static string Particular {
            get {
                return ResourceManager.GetString("Particular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Name.
        /// </summary>
        public static string PartyName {
            get {
                return ResourceManager.GetString("PartyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Terms.
        /// </summary>
        public static string PaymentTerms {
            get {
                return ResourceManager.GetString("PaymentTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Entries.
        /// </summary>
        public static string PurchaseEntries {
            get {
                return ResourceManager.GetString("PurchaseEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order Number.
        /// </summary>
        public static string PurchaseOrderNumber {
            get {
                return ResourceManager.GetString("PurchaseOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save And Print.
        /// </summary>
        public static string SaveAndPrint {
            get {
                return ResourceManager.GetString("SaveAndPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Payment.
        /// </summary>
        public static string SelectPayment {
            get {
                return ResourceManager.GetString("SelectPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Vendor.
        /// </summary>
        public static string SelectVendor {
            get {
                return ResourceManager.GetString("SelectVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Charges.
        /// </summary>
        public static string ShippingCharges {
            get {
                return ResourceManager.GetString("ShippingCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        public static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxable Amt.
        /// </summary>
        public static string TaxableAmt {
            get {
                return ResourceManager.GetString("TaxableAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date Nepali.
        /// </summary>
        public static string ToDateNepali {
            get {
                return ResourceManager.GetString("ToDateNepali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date (Nepali).
        /// </summary>
        public static string TransactionDateNepali {
            get {
                return ResourceManager.GetString("TransactionDateNepali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        public static string TransactionType {
            get {
                return ResourceManager.GetString("TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Contact Person.
        /// </summary>
        public static string VendorContactPerson {
            get {
                return ResourceManager.GetString("VendorContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Email.
        /// </summary>
        public static string VendorEmail {
            get {
                return ResourceManager.GetString("VendorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name.
        /// </summary>
        public static string VendorName {
            get {
                return ResourceManager.GetString("VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Phone Number.
        /// </summary>
        public static string VendorPhoneNumber {
            get {
                return ResourceManager.GetString("VendorPhoneNumber", resourceCulture);
            }
        }
    }
}
